name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Deploy to Dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        env:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: 'broadcastt.xyz'
          app-name: 'docs'
